name: EndoRM

params:
  aggregate:
    mode: discounted_sum
    gamma: 0.93
    clip_min: 0.00
    logprob_cache_path: "cache/endorm_logprob.npz"
    reuse_logprob_cache: false
    save_logprob_cache: false

sglang_cfg:
  engine:
    tp_size: 1
    dp_size: 1
    mem_fraction_static: 0.7
  sampling_params:
    temperature: 0.0
    top_p: 1.0
    top_k: -1
